version: '3'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "7860:7860"
    volumes:
      - /tmp/flask_sessions:/tmp/flask_sessions
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
       - SESSION_FILE_DIR=/app/flask_sessions
    restart: always
